baseURL = 'https://dx96.netlify.app'
languageCode = 'en-us'
title = 'Alexander Atte'
theme = 'terminal'
keywords = [
  'durdenx96',
  'alex',
  'alexander atte',
  'github',
  'programming',
  'development',
  'programmer',
  'developer',
  'alexanderatte@gmail.com',
]
enableEmoji = true
enableRobotsTXT = true

[pagination]
pagerSize = 5

[params]
contentTypeName = "posts"
showMenuItems = 2
showLanguageSelector = false
fullWidthTheme = false
centerTheme = true
autoCover = true
showLastUpdated = false

# [markup.goldmark.renderer]
# unsafe = true

[security]
[security.funcs]
getenv = ["^HUGO_"]

[languages]
[languages.en]
languageName = "English"
title = "Alexander Atte"

[languages.en.params]
subtitle = "Hello, My name is Alexander Atte. A.K.A @durdenx96..."
menuMore = "More"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"

[languages.en.params.logo]
logoText = "the memory palace"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 1

[[languages.en.menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts"
weight = 2
